### PR TITLE
Theoxuan patch 1

### PR DESCRIPTION
**Pull request by theoxuan**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] [local build the book](https://github.com/ocademy-ai/machine-learning/blob/main/CONTRIBUTING.md#build-the-book)
- [ ] review the artifacts from local build
- [ ] [local build the slides](https://github.com/ocademy-ai/machine-learning/blob/main/CONTRIBUTING.md#build-the-slides-optional) if appliable
- [ ] Unit test if appliable

# Checklist:

- [ ] My code follows the [style guidelines](https://github.com/ocademy-ai/machine-learning/blob/main/STYLE_GUIDE.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have applied tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by WHQWHQWHQ** [comment]
[Data quality](https://en.wikipedia.org/wiki/Data_quality) refers to the state of qualitative or quantitative pieces of information. Generally speaking, high-quality data could "fit for [its] intended uses in operations, decision making and planning"{cite}`redman2008data`{cite}`fadahunsi2019protocol`{cite}`fadahunsi2021information`. Data quality is a widely used concept and is split into multiple dimensions traditionally. This section will discuss the most common ones to Machine Learning data engineering, including completeness, duplicates, outlier, and consistency.

:::{seealso}
- The ***Overview and importance of data quality for machine learning tasks***{cite}`jain2020overview` lecture recording at KDD 2020, [Part 1](https://www.youtube.com/watch?v=30uRhUZ78gQ), [Part 2](https://www.youtube.com/watch?v=5uAwssnBnGE), [Part 3](https://www.youtube.com/watch?v=IDwQsYKBQqs). 
- [Data Science for Beginners - Introduction to Data Ethics
](https://microsoft.github.io/Data-Science-For-Beginners/#/1-Introduction/02-ethics/README)
:::

I just checked data-engineering.ipynb, I think the cite must be on COS, or delete them.And some cite in Data quality is invalid. It's better for you to check your file in JupyterLab.
According to error: "Figure caption must be a paragraph or empty comment" indicates a chart caption-related problem, usually caused by incorrectly formatted chart captions in the Markdown unit

**Comment by bestfw** [comment]
If data-engineering.ipynb hinder you submit PR, just delete this file and resolve md file. I will check this file.

**Comment by bestfw** [comment]
Please merge the contents of the latest main branch and build again, if you can't, save the file locally then create a new synchronized latest branch and commit a PR.

**Comment by bestfw** [comment]
As I say in Wechat, Execution failed error is Github actions cannot run ipynb file successfully, so what you should do is running locally to see if this file can be executed successfully, or if it takes too long to be executed.
If you find ipynb files like what I say, please add them to execute.
Also you can refer the PR I submit: 'https://github.com/ocademy-ai/machine-learning/pull/604'

**Pull request closed without merging**
