### PR TITLE
Solve all autoencoder assignments dataset problems

### PR DESCRIPTION
**Pull request by bestfw**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] [local build the book](https://github.com/ocademy-ai/machine-learning/blob/main/CONTRIBUTING.md#build-the-book)
- [x] review the artifacts from local build
- [ ] [local build the slides](https://github.com/ocademy-ai/machine-learning/blob/main/CONTRIBUTING.md#build-the-slides-optional) if appliable
- [ ] Unit test if appliable

# Checklist:

- [ ] My code follows the [style guidelines](https://github.com/ocademy-ai/machine-learning/blob/main/STYLE_GUIDE.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have applied tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by bestfw** [comment]
The model has not been exported and saved
PS: Because tensorflow cannot call the GPU, and it is suspected that having it in the same environment as pytorch will prevent pytorch from calling the GPU as well, we are currently creating an environment in docker where tensorflow can be used.

**Comment by bestfw** [comment]
In my testing down the road, there were three jobs that didn't work:
One I could not use the imgaug module;
One was using the TensorFlow API which doesn't support calls on symbolic objects and required code changes to save the model;
One was that for some reason it reported an error when training locally, and the same error when I downloaded the source file.

**Comment by bestfw** [comment]
In jobs where you can save models and import them for use:
One requires an additional installation of the umap module;
One using the pth file format causes some of the images to be out of the valid range expected by imshow and also requires modification.

**Comment by reveurmichael** [comment]
image

**Review by reveurmichael — APPROVED** [review]
OK

**Pull request merged**
