### PR TITLE
test for tutorial

### PR DESCRIPTION
**Pull request by HenryCheval**
I put some tutorials in the data,db for test
along with their authors in user table
user tutorials and tag tutorial added

### CODE REVIEW

**Comment by HenryCheval** [comment]
11.16
syllabus in course optimized
tutorials 50 added

**Comment by HenryCheval** [comment]
tutorials all added
along with their authors in user table
user tutorials and tag tutorial added
user tags not done yet

**Comment by HenryCheval** [comment]
It turned out usertag can be easily adressed with sql
usertag added

**Review by LongfeiH — APPROVED** [review]
OK

**Pull request merged**
