### PR TITLE
debug for building problem

### LINKED ISSUE #521: Transform introduction

### PR DESCRIPTION
**Pull request by Paradox-z**
# Description

fix code with /introduction and ..\open-machine-learning-jupyter-book\assignments\data-science\introduction-to-statistics-and-probability

Fixes #521 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] [local build the book](https://github.com/ocademy-ai/machine-learning/blob/main/CONTRIBUTING.md#build-the-book)
- [ ] review the artifacts from local build
- [ ] [local build the slides](https://github.com/ocademy-ai/machine-learning/blob/main/CONTRIBUTING.md#build-the-slides-optional) if appliable
- [ ] Unit test if appliable

# Checklist:

- [ ] My code follows the [style guidelines](https://github.com/ocademy-ai/machine-learning/blob/main/STYLE_GUIDE.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have applied tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by WHQWHQWHQ** [comment]
/home/runner/work/machine-learning/machine-learning/open-machine-learning-jupyter-book/data-science/introduction/introduction-to-statistics-and-probability.ipynb:1: WARNING: Pygments lexer name '{code' is not known
One symbol } is missing

**Comment by bestfw** [comment]
image
Like this error, you need to add --- in this place. Please fix these error soon.

**Comment by bestfw** [comment]
Please merge the contents of the latest main branch and build again, if you can't, save the file locally then create a new synchronized latest branch and commit a PR.
There is a modify in _config.yml file, I'm not sure that change will fix that, but can have a try.

**Comment by bestfw** [comment]
You can try to find which ipynb has the most codes then not submit it and try again.

**Comment by bestfw** [comment]
First, you should not submit multiple tasks into one PR, you should create another branch and submit another PR.
Second, as I say in Wechat, Execution failed error is Github actions cannot run ipynb file successfully, so what you should do is running locally to see if this file can be executed successfully, or if it takes too long to be executed.
If you find ipynb files like what I say, please add them to execute.
Also you can refer the PR I submit: 'https://github.com/ocademy-ai/machine-learning/pull/604'

**Comment by bestfw** [comment]
image
These two files are not in transform task, please delete them by commit from PR. If they are other task's file, please open a new branch and create a new PR.

**Comment by Paradox-z** [comment]
> image These two files are not in transform task, please delete them by commit from PR. If they are other task's file, please open a new branch and create a new PR.

Done. Could you redo the Merge action.

**Review by bestfw — APPROVED** [review]
Good jobs

**Pull request merged**
